const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

console.log('╔══════════════════════════════════════════════════════════════╗');
console.log('║     ZTAP BUILD v3.0 — IRONCLAD (HARDENED)                   ║');
console.log('╚══════════════════════════════════════════════════════════════╝');
console.log('');

// ──────────────────────────────────────────────────────────────────────────
// CRÍTICO 2 MITIGATION: No more admin_token.txt
// Admin HMAC secret is derived from server_secrets.enc (generated by keygen)
// ──────────────────────────────────────────────────────────────────────────
let adminToken;
let serverNonce;
try {
    const secrets = JSON.parse(fs.readFileSync('server_secrets.enc', 'utf8'));
    adminToken = secrets.adminSecret;
    serverNonce = secrets.serverNonce;
    console.log('[BUILD] Secretos cargados desde server_secrets.enc (derivados de passphrase)');
} catch (e) {
    console.error('[BUILD] ERROR FATAL: server_secrets.enc no encontrado.');
    console.error('[BUILD] Ejecuta primero: node keygen.js');
    process.exit(1);
}

// ──────────────────────────────────────────────────────────────────────────
// ALTO 3 MITIGATION: serverNonce adds entropy to route rotation
// HMAC(adminToken, dayNonce + ':' + hourlyNonce + ':' + serverNonce)
// The serverNonce is random per keygen cycle — prevents prediction even
// if the adminToken is leaked without the serverNonce.
// ──────────────────────────────────────────────────────────────────────────
const dayNonce = String(Math.floor(Date.now() / 86400000));
const hourlyNonce = String(Math.floor(Date.now() / 3600000));
const todayAdminPath = crypto.createHmac('sha256', adminToken)
    .update(dayNonce + ':' + hourlyNonce + ':' + serverNonce)
    .digest('hex');
const minutesLeft = Math.ceil((3600000 - (Date.now() % 3600000)) / 60000);

const masterPublicPem = fs.readFileSync('master_public.pem', 'utf8').trim();
const pemContents = masterPublicPem
    .replace('-----BEGIN PUBLIC KEY-----', '')
    .replace('-----END PUBLIC KEY-----', '')
    .trim();

// ──────────────────────────────────────────────────────────────────────────
// ALTO 4 MITIGATION: Obfuscation removed (Kerckhoffs' principle)
// Security resides in the keys, not in hiding the algorithm.
// Obfuscation was providing false confidence and increasing bug surface.
// Client code is now minified (dead code removal, whitespace strip) but
// NOT obfuscated. All secrets are injected at build time as before.
// ──────────────────────────────────────────────────────────────────────────
function minifyJS(code) {
    // String-aware comment stripper: skips // and /* */ inside quotes/backticks
    let result = '';
    let i = 0;
    while (i < code.length) {
        // String literals: skip through without modifying
        if (code[i] === "'" || code[i] === '"' || code[i] === '`') {
            const quote = code[i];
            result += code[i++];
            while (i < code.length && code[i] !== quote) {
                if (code[i] === '\\') { result += code[i++]; } // skip escaped char
                if (i < code.length) result += code[i++];
            }
            if (i < code.length) result += code[i++]; // closing quote
        }
        // Single-line comment (not inside string)
        else if (code[i] === '/' && code[i + 1] === '/') {
            while (i < code.length && code[i] !== '\n') i++;
        }
        // Multi-line comment
        else if (code[i] === '/' && code[i + 1] === '*') {
            i += 2;
            while (i < code.length - 1 && !(code[i] === '*' && code[i + 1] === '/')) i++;
            i += 2;
        }
        else {
            result += code[i++];
        }
    }
    return result
        .replace(/^\s+/gm, '')                      // Remove leading whitespace
        .replace(/\n{2,}/g, '\n')                    // Collapse blank lines
        .trim();
}

console.log('[BUILD] Procesando ztap-worker.js...');
const workerRaw = fs.readFileSync('src/ztap-worker.js', 'utf8');
const workerMinified = minifyJS(workerRaw);
const goldHash = crypto.createHash('sha512').update(workerMinified).digest('hex');

console.log('[BUILD] Inyectando GOLD_HASH y Master Key en client.js...');
const clientJsRaw = fs.readFileSync('src/client.js', 'utf8');
const clientJsInjected = clientJsRaw
    .replace('INJECT_MASTER_PUBLIC_KEY', pemContents)
    .replace('INJECT_EXPECTED_HASH', goldHash);

console.log('[BUILD] Procesando client.js...');
const clientMinified = minifyJS(clientJsInjected);

console.log('[BUILD] Procesando admin-client.js...');
const adminClientRaw = fs.readFileSync('src/admin-client.js', 'utf8');
const adminClientMinified = minifyJS(adminClientRaw);

fs.mkdirSync('public', { recursive: true });
fs.writeFileSync('public/ztap-worker.js', workerMinified);
fs.writeFileSync('public/client.js', clientMinified);
fs.writeFileSync('public/admin-client.js', adminClientMinified);
fs.copyFileSync('src/index.html', 'public/index.html');
fs.copyFileSync('src/admin.html', 'public/admin.html');
fs.writeFileSync('public/GOLD_HASH.txt', goldHash);

console.log('');
console.log('══════════════════════════════════════════════════════════════════');
console.log('  BUILD COMPLETADO — SISTEMA IRONCLAD v3.0 (HARDENED)');
console.log('══════════════════════════════════════════════════════════════════');
console.log('');
console.log('  [ADMIN] Ruta dinámica (hourly rotation + serverNonce):');
console.log(`  /${todayAdminPath}`);
console.log('  (Expira en ' + minutesLeft + ' min)');
console.log('');
console.log('  [HARDENING] Mitigaciones de Seguridad Activas:');
console.log('  1. Clave privada cifrada en reposo (scrypt + AES-256-GCM).');
console.log('  2. admin_token.txt ELIMINADO (derivado de passphrase).');
console.log('  3. Rutas admin con serverNonce (anti-predicción).');
console.log('  4. Ofuscación removida (principio de Kerckhoffs).');
console.log('  5. ECDH efímero para PFS en cada sesión.');
console.log('  6. Rate limiting granular + PoW adaptativo.');
console.log('  7. Sanitización de inputs + manejo de errores.');
console.log('  8. Worker Integrity: GOLD_HASH pre-spawning.');
console.log('');
console.log('  GOLD_HASH: ' + goldHash.slice(0, 32) + '...');
console.log('══════════════════════════════════════════════════════════════════');
console.log('');
